name: 'Coda-Changelog'
description: 'A Github action that sends your commit information to a Coda document'
author: 'Steamclock Software'
inputs:
  commits: 
    description: 'list of commits'
  doc-id:
    description: 'id of coda document'
  token:
    description: 'Defines the token used to access a specific Coda document'
runs:
  using: 'node12'
  main: 'dist/index.js'
