name: 'Coda-Changelog'
description: 'A Github action that sends your commit information to a Coda document'
author: 'Steamclock Software'
inputs:
  commits:
    description: 'Github event commits'
  fromTag:
    description: 'Tag to indicate when to fetch commits from for initial write to table'
  token:
    description: 'Github access token'
  branch:
    description: 'Current branch name'
  table:
    description: 'Name of coda table'
    default: "Unreleased Changes"
  doc-id:
    description: 'Coda document id'
  coda-token:
    description: 'Coda API Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
