name: 'Coda-Changelog'
description: 'A Github action that sends your commit information to a Coda document'
author: 'Steamclock Software'
inputs:
  commits: # change this
    required: true
    description: 'list of commits'
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
