name: 'Coda-Changelog'
description: 'A Github action that sends your commit information to a Coda document'
author: 'Steamclock Software'
inputs:
  fromTag:
    description: 'tag to indicate when to fetch commits from for initial write to table'
  token:
    description: 'github access token'
  branch:
    description: 'current branch name'
  table:
    description: 'name of coda table to write too'
    default: "Unreleased Changes"
  doc-id:
    description: 'id of coda document'
  coda-token:
    description: 'Defines the token used to access a specific Coda document'
runs:
  using: 'node12'
  main: 'dist/index.js'
